web:
   image: php:7.2-apache
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb:5.5
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"
